GIScience/orstools-qgis-plugin

- metadata.txt
- osm_tools_access.py
- osm_tools_dialog_base.ui
- osm_tools_geocode.py
- osm_tools_routing.py
- resources_rc.py
> Os mtools v0.3.1 acc groups

- osm_tools.py
- osm_tools_access.py
- osm_tools_dialog_base.ui
- osm_tools_geocode.py
- osm_tools_routing.py
- resources_rc.py
Extract improvements to v0.3.1 without the GH additions
> Os mtools include graph hopper

- isochrones.py
Leverage the ability to return a unique id from the API for every unique request. This should address #52 by allowing the data to be joined on. On point selections, that have no inherent feature id, this defaults to `-1`
> Add feature id of the input layer to the resulting isochron feature

- ORStools/__init__.py
> explicit encoding of metadata.txt to utf-8

- ORStools/proc/matrix_proc.py
> fix mixup of source and destination layer in matrix algo (#92)

- ORStools/gui/ORStoolsDialog.py
- ORStools/gui/directions_gui.py
> Correctly parse avoid_polygons

- ORStools/metadata.txt
- ORStools/proc/provider.py
Fixes #119 
Compare [this commit](https://github.com/jdugge/BufferByPercentage/pull/14/commits/04269ff6b25433253259294eb480a10e4b353403) in a different plugin for (a bit) of reasoning.
> Fix incorrect ownership of algorithms in processing provider

- CHANGELOG.md
- ORStools/metadata.txt
including release instructions
replace changelog in metadata.txt with unreleased changes
and link to complete changelog on github
> Add CHANGELOG.md

- CHANGELOG.md
- ORStools/metadata.txt
- ORStools/proc/directions_lines_proc.py
- ORStools/proc/directions_points_layer_proc.py
- ORStools/proc/directions_points_layers_proc.py
- ORStools/proc/isochrones_layer_proc.py
- ORStools/proc/matrix_proc.py
Following 7e95813a, this is now also fixed in all other processing
algorithms.
> Processing algorithms run with missing field

- CHANGELOG.md
- ORStools/help/directions_from_points_1_layer.help
- ORStools/help/directions_from_points_2_layers.help
- ORStools/metadata.txt
- ORStools/proc/directions_points_layer_proc.py
- ORStools/proc/directions_points_layers_proc.py
Allow custom waypoint ordering.
Fixes #142
> Custom waypoint ordering

- CHANGELOG.md
- ORStools/common/isochrones_core.py
- ORStools/help/isochrones_from_layer.help
- ORStools/help/isochrones_from_point.help
Addresses #137.
Data can be extracted via the `Create points layer from table` builtin processing algorithm.
> Add isochrone centers to isochrone attributes

- .gitignore
- CHANGELOG.md
- ORStools/common/__init__.py
- ORStools/common/directions_core.py
- ORStools/help/directions_from_points_1_layer.help
- ORStools/help/directions_from_points_2_layers.help
- ORStools/help/directions_from_polylines_layer.help
- ORStools/help/isochrones_from_layer.help
- ORStools/help/isochrones_from_point.help
- ORStools/help/matrix_from_layers.help
- ORStools/proc/base_processing_algorithm.py
- ORStools/proc/directions_lines_proc.py
- ORStools/proc/directions_points_layer_proc.py
- ORStools/proc/directions_points_layers_proc.py
- ORStools/proc/isochrones_layer_proc.py
- ORStools/proc/isochrones_point_proc.py
- ORStools/proc/matrix_proc.py
This PR implements the features mentioned in the title for the processing algorithms.
This has been asked for many times. TODO: add link
The special-casing in TODO: list file can be dropped once ors > 6.6.1 is released.
> Implement avoid_{features,borders,polygons,countries} for processing algos

- CHANGELOG.md
- ORStools/gui/ORStoolsDialogConfig.py
use the default url of a local ors instance for a new provider entry
> Adjust default provider url

- CHANGELOG.md
- ORStools/proc/directions_lines_proc.py
- ORStools/proc/directions_points_layer_proc.py
- ORStools/proc/isochrones_layer_proc.py
- ORStools/proc/matrix_proc.py
> Accept lines with Z/M

- ORStools/gui/ORStoolsDialog.py
Done as in [here](https://github.com/borysiasty/plugin_reloader/blob/861e87ce072e9f80c4f1b6d061370d6bbb7ff19d/reloader_plugin.py#L135) as suggested by @koebi.
> Add keyboard shortcut functionality

- ORStools/common/client.py
- ORStools/gui/ORStoolsDialog.py
- ORStools/proc/base_processing_algorithm.py
- ORStools/proc/directions_lines_proc.py
- ORStools/proc/provider.py
Get name of files using inspect and add them to the request header.
> feat: add origin of request to request header

- CHANGELOG.md
- ORStools/gui/ORStoolsDialog.py
> fix: TypeError if no SVGPaths are set

- CHANGELOG.md
- ORStools/gui/linestyle.qml
> 218 style not rendering correctly in qgis 316

- ORStools/proc/directions_points_layer_proc.py
Input input_points list was appended by lists of points not the points themselves.
> fix: RequestsException with multi points layers and TSP option selected in point layer proc

- CHANGELOG.md
- ORStools/common/directions_core.py
- ORStools/proc/directions_lines_proc.py
- ORStools/proc/directions_points_layers_proc.py
To make the csv feature work with points_layers_proc
> Add csv_column parameter to request in points_layers_proc

- ORStools/ORStoolsPlugin.py
> fix: wrap locale reading in try/except statement

- ORStools/gui/ORStoolsDialog.py
> fix: Adding waypoints to GUI after calculating a route leads to error

- CHANGELOG.md
- ORStools/gui/ORStoolsDialog.py
- ORStools/gui/ORStoolsDialogUI.py
- ORStools/gui/ORStoolsDialogUI.ui
- ORStools/i18n/orstools_de.ts
- ORStools/utils/maptools.py
- tests/conftest.py
- tests/test_gui.py
- tests/test_proc.py
Closes #285.
I've added the right click as an exit option too. That might be just as intuitive as the ESC button. Opinions welcome!
> Exit digitization on right click and ESC button

- ORStools/gui/ORStoolsDialog.py
Closes #168 and supersedes #169.
> feat: save state of provider combobox

- ORStools/gui/ORStoolsDialog.py
- ORStools/proc/base_processing_algorithm.py
- ORStools/proc/directions_lines_proc.py
- ORStools/proc/directions_points_layer_proc.py
- ORStools/proc/directions_points_layers_proc.py
- ORStools/proc/export_proc.py
- ORStools/proc/isochrones_layer_proc.py
- ORStools/proc/isochrones_point_proc.py
- ORStools/proc/matrix_proc.py
- ORStools/proc/snap_layer_proc.py
- ORStools/proc/snap_point_proc.py
- ORStools/utils/router.py
> refactor: rename output names of procs and append date and time
